# Manipulation de données Python avec `pandas` : Partie 1
* * *
<div class="alert alert-success">  
    
### Objectifs d'apprentissage
    
* Se familiariser avec `pandas` et l'objet central `DataFrame`
* Appliquer les techniques de base de manipulation de données dans `pandas`
* Comprendre la flexibilité de la bibliothèque `pandas`
</div>

## Importation et visualisation des données
Nous allons travailler avec [des données sur le chômage européen provenant d'Eurostat](https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Unemployment_statistics). Il existe plusieurs fichiers `.csv` liés à ce thème avec lesquels nous travaillerons dans ce sujet, tous relatifs aux taux de chômage dans les pays européens.

Commençons par importer `pandas` en utilisant l'abréviation conventionnelle `pd`.

In [1]:
# Importer pandas avec l'alias `pd`
import pandas as pd

# Nous importons souvent NumPy (numerical python) avec pandas
# nous l'importons avec l'alias `np`
import numpy as np

`pandas` possède une fonction `read_csv()` qui nous permet d'importer facilement des données tabulaires. La fonction retourne un objet `DataFrame`, qui est l'objet principal que `pandas` utilise pour représenter les données tabulaires.

La fonction `pd.read_csv` peut être paramétrée pour s'adapter à différents types de fichiers csv. Ici, nous sommes obligé de spécifier le séparateur car pandas utilise la virgule par défaut.

In [3]:
unemployment = pd.read_csv('unemployment.csv',sep=",")

Vous avez créé un `DataFrame` `pandas`. Nous pouvons examiner nos données en utilisant la méthode `.head()`. Par défaut, cela affiche l'en-tête (noms des colonnes) et les **cinq** premières lignes.

Si vous souhaitez voir un autre nombre de lignes, vous pouvez passer un entier à .head() pour retourner ce nombre de lignes. Par exemple, unemployment.head(6) retournerait les six premières lignes.

In [5]:
unemployment.head(6)

,country,seasonality,year_month,unemployment,unemployment_rate,date,year,month
0,at,sa,1993.01,144000,3.8,1/1/1993,1993,1
1,at,sa,1993.02,145000,3.8,2/1/1993,1993,2
2,at,sa,1993.03,147000,3.9,3/1/1993,1993,3
3,at,sa,1993.04,149000,3.9,4/1/1993,1993,4
4,at,sa,1993.05,151000,4.0,5/1/1993,1993,5
5,at,sa,1993.06,152000,4.0,6/1/1993,1993,6

Pour trouver le nombre de lignes, vous pouvez utiliser l'attribut `.shape`, qui retourne un tuple : `(nombre de lignes, nombre de colonnes)`

In [4]:
unemployment.shape

(6438, 8)

Pour connaître les noms des colonnes, vous pouvez utiliser l'attribut `.columns`.

In [5]:
unemployment.columns

Index(['country', 'seasonality', 'year_month', 'unemployment',
       'unemployment_rate', 'date', 'year', 'month'],
      dtype='str')

Pour connaître les types de données, nous utilisons l'attribut `.dtypes`, qui nous indique quelles colonnes contiennent des données numériques (par ex. types `float64` ou `int64`) et lesquelles contiennent du texte (par ex. types `object`)

In [6]:
unemployment.dtypes

country                  str
seasonality              str
year_month           float64
unemployment           int64
unemployment_rate    float64
date                     str
year                   int64
month                  int64
dtype: object

## Fonction de statistiques de base

La  méthode `describe()` génère diverses statistiques décrivant le dataframe. C'est une méthode puissante qui retournera beaucoup d'informations, alors avant de l'exécuter, voyons exactement ce qu'elle fait.

💡 **Astuce** : La [documentation `pandas`](http://pandas.pydata.org/pandas-docs/stable/) contient des informations exhaustives sur chaque fonction, objet, etc. dans `pandas`. Elle peut être un peu difficile à naviguer seule, il est donc typique d'interagir avec la documentation principalement via des recherches Google.

Voici un flux de travail général pour en apprendre davantage sur une fonction dans `pandas` :
1. Recherchez la fonction `pandas` sur Google, par ex. "pandas {insérer le nom de la fonction}"
2. Trouvez un résultat de pandas.pydata.org (la documentation pandas)
3. Lisez le résumé de ce que fait la fonction (en haut de la page), examinez ses arguments et ce qu'elle retourne.

<span color="purple">📝 **Question :** Avant d'exécuter le code suivant, essayez d'utiliser le flux de travail général détaillé ci-dessus pour découvrir ce que `.describe()` retourne. </span>

In [7]:
unemployment.describe()

        year_month  unemployment  unemployment_rate         year        month
count  6438.000000  6.438000e+03        6116.000000  6438.000000  6438.000000
mean   1999.431230  8.173948e+05           8.165598  1999.369525     6.170550
std       7.466699  1.042835e+06           3.892202     7.466812     3.426694
min    1983.010000  2.000000e+03           1.300000  1983.000000     1.000000
25%    1994.090000  1.420000e+05           5.200000  1994.000000     3.000000
50%    2001.010000  3.155000e+05           7.600000  2001.000000     6.000000
75%    2006.010000  1.489500e+06           9.900000  2006.000000     9.000000
max    2010.120000  4.773000e+06          20.600000  2010.000000    12.000000

⚠️ **Avertissement** : `.describe()` se comportera différemment selon les types de vos données, ou `dtypes`. Si votre `DataFrame` inclut à la fois des `dtypes` numériques et object (par ex., chaînes), il résumera par défaut **uniquement les données numériques** (comme montré ci-dessus). Si `.describe()` est appelé sur un `DataFrame` qui contient uniquement des chaînes, il retournera le nombre, le nombre de valeurs uniques et la valeur la plus fréquente avec son nombre.

## 🥊 Défi 1
**Configuration**  
Nous avons précédemment importé des données sur le **chômage** dans `pandas` en utilisant la fonction `read_csv` et un chemin de fichier relatif. `read_csv` nous permet également d'importer des données en utilisant une URL comme chemin de fichier.

Un fichier .csv avec des données sur les pays du monde et leurs abréviations se trouve à l'URL suivante :

[https://raw.githubusercontent.com/dlab-berkeley/introduction-to-pandas/master/data/countries.csv](https://raw.githubusercontent.com/dlab-berkeley/introduction-to-pandas/master/data/countries.csv)

Nous pouvons charger ces données directement comme suit :

In [11]:
# countries_url = 'https://raw.githubusercontent.com/dlab-berkeley/Python-Data-Wrangling/main/data/countries.csv'
countries_url = './countries.csv'
countries = pd.read_csv(countries_url)

In [12]:
countries.head()

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

**Défi**  
Chaque fois que nous ouvrons un nouveau DataFrame, il est important d'obtenir une compréhension de base de sa structure.

En utilisant les méthodes et attributs que nous venons de discuter, **répondez aux questions suivantes** sur `countries` :

1. Quelles colonnes contient `countries` ?
2. Combien de lignes et de colonnes contient-il ?
3. Quelles sont les valeurs minimale et maximale des colonnes avec des données numériques ?

<details><summary><a>Cliquez pour un indice</a></summary>
Indice : envisagez d'utiliser <code>.columns</code>, <code>.shape</code> et <code>.describe()</code> ici.
</details>

In [20]:
# VOTRE CODE ICI
countries.count()

countries.max()

country                            uk
google_country_code                TR
country_group                  non-eu
name_en                United Kingdom
name_fr                       Turquie
name_de                    Österreich
latitude                    64.950159
longitude                   35.439795
dtype: object

In [ ]:
# VOTRE CODE ICI

In [ ]:
# VOTRE CODE ICI

<a id='indexing'></a>
## Indexation des données
La manipulation de données dans un DataFrame nécessite souvent d'extraire des lignes et/ou colonnes spécifiques. C'est ce qu'on appelle l'**indexation**. Nous avons déjà appris une manière simple d'indexer nos données en utilisant `.head()`, qui isolait les cinq premières lignes de nos données. Maintenant, nous allons apprendre des méthodes plus flexibles et puissantes pour l'indexation.


L'indexation fonctionne de manière très similaire dans `pandas` comme en Python standard, mais avec quelques différences clés. Dans `pandas`, l'indexation repose sur le référencement des lignes d'un DataFrame puis de ses colonnes <span>&#8594;</span> `[lignes, colonnes]`.

In [ ]:
# VOTRE CODE ICI
countries.loc[3, 'google_country_code']

## `.loc` et `iloc`

Nous avons 2 façons d'indexer sur un dataframe : par indices (avec `iloc`) par index ou étiquettes (avec `loc`).

In [13]:
countries.loc[:4, :]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

Le code `countries.loc[:4, :]` exécute ce qui suit :  
- <code>countries.loc[<mark style="background: yellow">**:4**</mark>, :]</code> <span>&#8594;</span> Sélectionne les lignes jusqu'à l'index 4
- <code>countries.loc[:4,<mark style="background: yellow"> **:**</mark>]</code> <span>&#8594;</span>
 Sélectionne toutes les colonnes

Ce format nous permet de sélectionner de manière flexible des plages de lignes et de colonnes en même temps. Considérez cet exemple plus complexe :

In [14]:
countries.loc[2:4, 'name_en':'name_de']

    name_en   name_fr    name_de
2  Bulgaria  Bulgarie  Bulgarien
3   Croatia   Croatie   Kroatien
4    Cyprus    Chypre     Zypern

Ce code a exécuté ce qui suit :  
- <code>countries.loc[<mark style="background: yellow">**2:4**</mark>, 'name_en':'name_de']</code> -> Sélectionne les lignes de l'étiquette 2 jusqu'à l'étiquette 4
- <code>countries.loc[2:4, <mark style="background: yellow">**'name_en'::'name_de'**</mark>]</code> -> Sélectionne les colonnes, de la colonne `name_en` à la colonne `name_de`

## 🥊 Défi 2 : Indexation avec `.loc`

Pratiquons un peu avec l'opérateur `.loc`.  

<span style="color:purple">Sélectionnez les lignes 10 à 20, puis calculez leur `latitude` moyenne </span>
<details>
    <summary><a>Cliquez pour un indice</a></summary>
    Cela peut être fait en utilisant <code>`.loc`</code> et <code>`.mean()`</code>, tout en une seule ligne de code : <code>countries.loc[{votre sélection de lignes}, {votre sélection de colonnes}].mean()</code>
</details>

In [ ]:
# VOTRE CODE ICI

<a id='boolean'></a>
## Indexation booléenne
Maintenant que nous avons revu les bases de l'indexation, passons à une extension extrêmement puissante -- "**l'indexation booléenne**." L'indexation booléenne fait référence au filtrage des données basé sur un test logique. Tout d'abord, rappelez-vous comment fonctionnent les booléens et les tests logiques en Python standard :

In [15]:
"D-Lab" == "D-Lab"

True

In [ ]:
"D-Lab" == "H-Lab"

False

In [ ]:
7 > 7

False

Nous utiliserons ce même style de test logique dans `pandas` pour exécuter l'indexation booléenne.   

## Exemple : trouver les pays hors de l'UE
Remarquez dans le dataframe `countries` illustré ci-dessous que nous avons une colonne, `country_group`, qui nous indique si un pays est dans l'Union européenne (UE) ou non. Nous allons faire un exemple d'indexation booléenne sur ces cinq premières lignes.

*Note : La Croatie fait partie de l'UE depuis 2013. Les données ne sont pas toujours correctes !*

In [16]:
# Crée un dataframe de test plus petit
# pour montrer comment fonctionne l'indexation booléenne
test = countries.loc[20:25, :]

In [17]:
test

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.556460,12.665766
21,pl,PL,eu,Poland,Pologne,Polen,51.918907,19.134334
22,pt,PT,eu,Portugal,Portugal,Portugal,39.558069,-7.844941
23,ro,RO,eu,Romania,Roumanie,Rumänien,45.942611,24.990152
24,sk,SK,eu,Slovakia,Slovaquie,Slowakei,48.672644,19.700032
25,si,SI,eu,Slovenia,Slovénie,Slowenien,46.149259,14.986617

Utilisons cette colonne pour filtrer nos données uniquement aux pays hors de l'Union européenne. Les étapes sont les suivantes :
1. Sélectionner la colonne que nous utiliserons comme filtre : `test['country_group']` ou `test.loc[:, 'country_group']`

In [18]:
test['country_group']

20    non-eu
21        eu
22        eu
23        eu
24        eu
25        eu
Name: country_group, dtype: object

2. Déterminer quelles lignes dans cette colonne sont égales à "non-eu" -- ce qui indique que le pays est hors de l'Union européenne : `test['country_group'] == 'non-eu'`. La sortie de ce code est ce qu'on appelle un **masque booléen**.

In [19]:
test['country_group'] == 'non-eu'

20     True
21    False
22    False
23    False
24    False
25    False
Name: country_group, dtype: bool

3. Utiliser le masque booléen pour indexer uniquement les lignes qui ont satisfait le test : `test[test['country_group'] == 'non-eu']`

In [20]:
test[test['country_group'] == 'non-eu']

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.55646,12.665766

Et voilà l'indexation booléenne ! Nous avons utilisé un test d'égalité (`countries['country_group'] == 'non-eu'`), mais nous pouvons utiliser une variété de tests et de conditions différents pour indexer nos données.

Par exemple, nous pourrions vouloir trouver les pays avec une longitude supérieure à un certain seuil, comme 25 (notez que nous allons revenir à l'utilisation du DataFrame complet `countries` maintenant) :

In [21]:
countries[countries['longitude'] > 25]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682
7,ee,EE,eu,Estonia,Estonie,Estland,58.592469,25.806950
8,fi,FI,eu,Finland,Finlande,Finnland,64.950159,26.067564
28,tr,TR,non-eu,Turkey,Turquie,Türkei,38.952942,35.439795

## 🥊 Défi 3 : Indexation booléenne

Allons un peu plus loin en indexation booléenne avec un problème.
1. Trouvez la longitude moyenne des pays dans nos données, assignez-la à la variable `average_long`
2. Trouvez les pays qui ont une longitude "supérieure à la moyenne"
<details>
    <summary><a>Cliquez pour un indice</a></summary>
    Calculez la longitude moyenne des données : <code>countries['longitude'].mean()</code> et sauvegardez-la dans une variable <code>average_long</code>. Ensuite, vous pouvez utiliser cette variable pour créer un masque booléen pour l'indexation : <code>countries['longitude'] > average_long</code>
</details>

In [ ]:
# VOTRE CODE ICI

In [ ]:
# VOTRE CODE ICI

## Indexation booléenne avec conditions multiples
Nous pouvons faire une indexation booléenne en utilisant autant de tests logiques que nous le souhaitons en enveloppant chaque test dans des parenthèses (`()`) et en utilisant l'opérateur ET (`&`) ou l'opérateur OU (`|`)

In [ ]:
# Sélectionne les pays avec une longitude supérieure à 25 mais inférieure à 30
countries[(countries['longitude'] > 25) & (countries['longitude'] < 30)]

In [ ]:
# Sélectionne les pays avec une longitude supérieure à 30 ou inférieure à 0
countries[(countries['longitude'] > 30) | (countries['longitude'] < 0)]

# Manipulation de données Python avec `pandas` : Partie 2
* * *

L'attribut date est de type `object`. Pour pouvoir le manipuler pour des opérations de transformation, nous devons le convertir en type `datetime`.

In [22]:
unemployment.dtypes

country               object
seasonality           object
year_month           float64
unemployment           int64
unemployment_rate    float64
date                  object
year                   int64
month                  int64
dtype: object

In [23]:
unemployment['date'] = pd.to_datetime(unemployment['date'])

<a id='missing'></a>
## Valeurs manquantes

Une des premières étapes du nettoyage des données est d'identifier et de traiter les données manquantes.
`pandas` fournit diverses méthodes pour explorer et traiter les "données manquantes", dont l'une est `.isna()`

In [24]:
unemployment.isna()

,country,seasonality,year_month,unemployment,unemployment_rate,date,year,month
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
6433,False,False,False,False,False,False,False,False
6434,False,False,False,False,False,False,False,False
6435,False,False,False,False,False,False,False,False
6436,False,False,False,False,False,False,False,False
6437,False,False,False,False,False,False,False,False

La méthode `.isna()` retourne une valeur booléenne correspondante pour chaque entrée dans le DataFrame `unemployment`. En Python, `True` est équivalent à 1 et `False` est équivalent à 0. Ainsi, lorsque nous additionnons les résultats par colonne (avec `.sum()`), nous obtenons un décompte du nombre **total** de valeurs manquantes par colonne :

In [25]:
unemployment.isna().sum()

country                0
seasonality            0
year_month             0
unemployment           0
unemployment_rate    322
date                   0
year                   0
month                  0
dtype: int64

C'est une astuce très utile, et elle nous montre que la seule colonne avec des valeurs manquantes est `unemployment_rate`.

Il existe une grande variété d'approches pour traiter les données manquantes. Une approche de base serait de **supprimer toute ligne avec un enregistrement de taux de chômage manquant** :

In [ ]:
unemployment.dropna(subset=['unemployment_rate'])

L'exécution simple de la méthode `.dropna()` ne modifie pas réellement nos données -- elle fait une copie puis supprime les lignes manquantes pour cette copie. Afin de sauvegarder notre modification, nous devrons redéfinir le DataFrame `unemployment` avec notre copie modifiée :

In [ ]:
unemployment = unemployment.dropna(subset=['unemployment_rate'])

**💡 Astuce :** Notez que les crochets `[]` sont nécessaires dans la méthode `dropna()` car le paramètre subset attend une liste de noms de colonnes. Même si vous ne spécifiez qu'une seule colonne, elle doit quand même être entourée de crochets pour indiquer qu'il s'agit d'une liste.

<a id='sorting'></a>
## Tri des valeurs

Nous avons travaillé avec des données sur les taux de chômage, il serait donc probablement utile de savoir quels sont les taux de chômage les plus élevés dans ces données. Pour cela, nous utiliserons la méthode `sort_values()` pour trier les données. Nous enchaînons `.head()` à la fin pour ne voir que les cinq premières lignes :

In [ ]:
unemployment.sort_values(by='date', ascending=False).head()

Le code ci-dessus crée une copie du `DataFrame`, triée en ordre **décroissant** (notez `ascending=False`), et affiche les cinq premières lignes.

## 🥊 Défi 4
Utilisons le tri pour répondre à une question pratique :  

<span style="color:purple">Quel pays a le taux de chômage le plus élevé dans nos données ?  
</span>
<details><summary><a>Cliquez pour un indice</a></summary>
1. Utilisez <code>.sort_values()</code> pour trier ces données en fonction du taux de chômage en ordre décroissant<br>
2. Sélectionnez la première ligne en utilisant <code>.head()</code> avec un argument pour le nombre de lignes<br>
</details>

In [ ]:
# VOTRE CODE ICI

<a id='merging'></a>
## Fusion de DataFrames

Notre DataFrame `unemployment` contient beaucoup d'informations intéressantes, mais malheureusement il manque les noms complets des pays. Nous avons ces informations dans le DataFrame `countries`, mais nous devons trouver un moyen de les combiner avec `unemployment`.

In [28]:
countries.head()

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

Parceque les données dont nous avons besoin sont stockées dans deux fichiers séparés, nous voudrons fusionner les données d'une manière ou d'une autre. Déterminons quelle colonne nous pouvons utiliser pour joindre ces données en jetant un œil à `unemployment`

In [29]:
unemployment.head()

,country,seasonality,year_month,unemployment,unemployment_rate,date,year,month
0,at,sa,1993.01,144000,3.8,1993-01-01,1993,1
1,at,sa,1993.02,145000,3.8,1993-02-01,1993,2
2,at,sa,1993.03,147000,3.9,1993-03-01,1993,3
3,at,sa,1993.04,149000,3.9,1993-04-01,1993,4
4,at,sa,1993.05,151000,4.0,1993-05-01,1993,5

Ces deux DataFrames semblent avoir une colonne `country` similaire, avec des codes à deux caractères pour chaque pays. Essayons de faire une fusion de ces deux ensembles de données basée sur la colonne `country`.

`pandas` inclut une fonction de fusion facile à utiliser qui accepte deux DataFrames et une colonne sur laquelle les fusionner :

In [30]:
unemployment_merged = pd.merge(unemployment, countries, on='country')

In [ ]:
unemployment_merged.head()

<a id='grouping'></a>
## Regroupement et agrégation des données

Et si nous voulions savoir combien d'observations existent pour chaque pays ? Pour ce faire, nous devons regrouper les pays, puis compter combien de fois chacun apparaît. En d'autres termes, nous allons **regrouper** nos données **par** une colonne spécifique, et calculer une quantité dans chaque groupe. L'opération "group-by" est une technique fondamentale utilisée avec les données tabulaires.  


(Pour ceux qui ont utilisé un logiciel de tableur comme Excel, vous pourriez reconnaître que nous parlons essentiellement de créer un "Tableau croisé dynamique")

## Regroupement simple avec `.value_counts()`
Pour les opérations de regroupement simples, nous pouvons utiliser la méthode `.value_counts()`. Nous exécutons généralement cela sur une seule colonne, et elle retournera un tableau montrant combien d'observations il y a pour chaque valeur unique dans la colonne.

In [ ]:
unemployment_merged['name_en'].value_counts()

Cela nous dit que nous avons beaucoup d'observations de données pour l'Italie, la France, la Suède, etc. et très peu d'observations pour la Turquie et l'Estonie.

## 🥊 Défi 5
Essayez d'utiliser `.value_counts()` sur le DataFrame pour découvrir combien d'observations proviennent d'enregistrements de l'UE par rapport à ceux hors UE

In [ ]:
### VOTRE CODE ICI

## Regroupement complexe avec `.groupby()`
Et si nous voulons faire quelque chose de plus complexe, comme découvrir **quel était le taux de chômage moyen pour les pays de l'UE et hors UE ?**. `.value_counts()` regroupe les données puis les compte, mais nous avons besoin d'une méthode qui peut regrouper les données puis les moyenner.

Ce type de question est un cas d'utilisation typique pour `.groupby()` -- qui nous permet de regrouper les données puis d'appliquer n'importe quelle fonction **d'agrégation** que nous voulons -- compter, moyenner, min, max, médiane, etc.

Dans notre exemple, nous voulons découvrir le taux de chômage moyen pour les pays de l'UE et hors UE, donc nous allons regrouper nos données en fonction de `country_group`.

Nous commençons avec la méthode `.groupby()`. Cela ne retourne pas réellement de données ou de sortie -- elle regroupe juste les données.

In [34]:
unemployment_merged.groupby('country_group')

Nous devons maintenant sélectionner une colonne de données et spécifier une fonction d'agrégation.

In [ ]:
unemployment_merged.groupby('country_group')['unemployment_rate'].mean()

En disséquant le code, nous avons dit à `pandas` :
1. <code>unemployment_merged<code><mark style="background: yellow">.groupby('country_group')</mark>['unemployment_rate'].mean()</code>

    Regrouper toutes nos lignes en fonction des valeurs uniques de la colonne `country_group` -- EU, non-EU
    
2. <code>unemployment_merged<code>.groupby('country_group')<mark style="background: yellow">['unemployment_rate']</mark>.mean()</code>

    Sélectionner la colonne `unemployment_rate`

2. <code>unemployment_merged<code>.groupby('country_group')['unemployment_rate']<mark style="background: yellow">.mean()</mark></code>

   Calculer la moyenne de la colonne sélectionnée (`unemployment_rate`) pour chaque groupe

Nous pouvons confirmer ce comportement en utilisant également l'indexation booléenne. Si nous indexons uniquement les enregistrements des pays de l'UE, sélectionnons la colonne `unemployment_rate`, puis calculons la moyenne, nous devrions obtenir 8,3, la même valeur calculée avec groupby :

In [36]:
boolean_index = unemployment_merged['country_group'] == 'eu'

In [ ]:
boolean_index

In [ ]:
unemployment_merged.loc[boolean_index, 'unemployment_rate'].mean()

Les forces de `.groupby()` par rapport à l'utilisation de l'indexation booléenne sont que `groupby()` passe très bien à l'échelle pour les scénarios avec de nombreux groupes, et nécessite beaucoup moins de code.

## 🥊 Défi 6

Utilisez `.groupby()` pour trouver le taux de chômage maximum pour chaque pays. Triez vos résultats du plus grand au plus petit.

Utilisez l'exemple ci-dessus comme guide.
<details><summary><a>Cliquez pour un indice</a></summary>
1. D'abord, utilisez <code>groupby()</code> pour regrouper sur "name_en". <br>
2. Ensuite, sélectionnez la colonne "unemployment_rate",<br>
3. Agrégez en utilisant <code>.max()</code> pour obtenir la valeur maximale.<br>
4. Enchaînez la méthode <code>.sort_values(ascending=False)</code>.
</details>

In [ ]:
# VOTRE CODE ICI

<a id='viz'></a>
## Visualisation des données
Dans le dernier défi, vous avez créé un tableau intéressant montrant le taux de chômage maximum historique que chaque pays a connu. Visualisons ce tableau sous forme de graphique à barres pour faciliter sa présentation.

Il existe différentes façons d'aborder la visualisation de données en Python -- nous couvrirons le traçage simple dans `pandas`, qui s'appuie sur les fonctionnalités de la bibliothèque `matplotlib`.

D'abord, nous allons définir une variable, `grouped`, avec le tableau que vous venez de créer :

In [ ]:
grouped = unemployment_merged.groupby('name_en')['unemployment_rate'].max().sort_values(ascending=False)
grouped

Maintenant nous pouvons le tracer. Dans `pandas`, la visualisation est aussi simple que d'appeler la méthode `.plot()`, puis de fournir des arguments optionnels (ici j'ai fourni `kind="barh"` pour créer un graphique à barres horizontales plutôt que le graphique linéaire par défaut). Ce qui suit est le taux de chômage maximum dans les pays des données pour chaque année :

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

grouped.plot(kind='barh')

# Nous ajoutons plt.show() pour afficher correctement le graphique
plt.show()

Essayons un autre graphique. Notre DataFrame complet est ce qu'on appelle une série temporelle -- nous avons des observations répétées des taux de chômage de divers pays au fil du temps. Nous traçons généralement les séries temporelles en utilisant des graphiques linéaires, alors créons un graphique linéaire examinant les taux de chômage de l'Espagne et du Portugal.  

Pour simplifier ce type de graphique, nous commencerons par faire de notre colonne de date l'index du DataFrame :

In [ ]:
unemployment_merged = unemployment_merged.set_index('date')

In [ ]:
unemployment_merged.head()

Nous utiliserons également l'indexation booléenne pour sélectionner les observations concernant l'Espagne. Nous sauvegarderons cela comme un nouveau DataFrame, `spain` :

In [ ]:
spain = unemployment_merged[unemployment_merged['name_en'] == 'Spain']
spain.head()

Maintenant nous pouvons facilement accéder au taux de chômage de l'Espagne, avec la date de chaque observation incluse comme index :

In [ ]:
spain['unemployment_rate']

Répétons la même indexation booléenne que nous avons utilisée pour l'Espagne, mais maintenant pour le Portugal :

In [ ]:
portugal = unemployment_merged[unemployment_merged['name_en'] == 'Portugal']

In [ ]:
spain.head()

In [ ]:
portugal.head()

Nous profiterons de la fonction `.plot()`, en appelant simplement `spain['unemployment_rate'].plot()`. Nous n'avons pas besoin de fournir d'argument à `.plot()` puisque nous utilisons le style de graphique par défaut -- un graphique linéaire. Nous ajoutons cependant quelques autres commandes pour ajouter une étiquette d'axe y et afficher le graphique.

In [ ]:
spain['unemployment_rate']

In [ ]:
spain['unemployment_rate'].plot()

# Nous ajoutons plt.show() pour afficher correctement le graphique
plt.show()

La superposition de graphiques impliquera simplement d'appeler plusieurs commandes `.plot()` dans la même cellule Jupyter. Nous pouvons également ajouter un style de base, comme des étiquettes, une légende et un titre.

In [ ]:
# Commandes de graphique
spain['unemployment_rate'].plot()
portugal['unemployment_rate'].plot()

# Style
plt.legend(["Espagne", "Portugal"])
plt.ylabel("Nombre")
plt.title("Taux de chômage en Espagne et au Portugal")
plt.show()